---
- name: Ensure APT official nginx key
  apt_key: 
    url: http://nginx.org/keys/nginx_signing.key

- name: Ensure APT official nginx repository (mainline)
  apt_repository: 
    repo: "deb http://nginx.org/packages/mainline/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"

- name: Update APT package cache
  apt:
    update_cache: yes

- name: Install the nginx packages
  package: 
    name: nginx
    state: present


